FROM gafiatulin/alpine-sbt
WORKDIR /scala-example

deps:
    COPY build.sbt ./
    COPY project project
    # RUN curl -L -o /root/.sbt/launchers/1.3.2/sbt-launch.jar https://repo.scala-sbt.org/scalasbt/maven-releases/org/scala-sbt/sbt-launch/1.3.2/sbt-launch.jar
    RUN sbt update
    SAVE IMAGE

build:
    FROM +deps
    COPY src src
    RUN sbt compile

test:
    FROM +deps
    COPY src src
    RUN sbt test

int1:
    FROM +deps
    # RUN curl -fsSL https://get.docker.com -o get-docker.sh
    # RUN sudo sh get-docker.sh
    # RUN apt-get update
    # RUN apt-get -y install docker
    # RUN apt-get -y install docker-compose 
    # RUN false
    COPY src src
    COPY docker-compose.yml ./ 
    WITH DOCKER 
        RUN false
        # RUN docker-compose up -d && docker-compose down 
    END

int2:
    FROM docker:dind
    RUN apk add docker-compose
    COPY docker-compose.yml ./
    WITH DOCKER 
        RUN FALSE
        # RUN docker-compose up -d && docker-compose down 
    END

docker:
    FROM +deps
    COPY src src
    RUN sbt assembly
    ENTRYPOINT ["java","-cp","target/scala-2.13/scala-example-assembly-1.0.jar","Main"]
    SAVE IMAGE scala-example:latest
